### ISSUE TITLE
Output limited to two lines at a time, making troubleshooting hard (and surely the output is not meant to be confined like that)

### ISSUE THREAD

**Issue by ghost** [linuxmint/gdebi#13]
Is this the place to file problems with Mint 19.0 (_sic_) and gbebi? (For, this repository is labelled as being about the version of gdebi with Mint _18_.)

I tried to install VirtualBox 6.0. So doing left my system in a bad state, not made easier by not being able to read the relevant erorr messages. I could not read them in that I could see only two lines at a time, no matter what I did with the window. Screenshot:

![image](https://user-images.githubusercontent.com/9998846/50263472-d79d3180-040d-11e9-838b-8fe9743a7b4d.png)

Might this be a theme problem? I'd change theme and run the installer again, but I don't want to risk rendering my system unbootable (which is what happened last time gdebi ran via the installer in question - I lost write access to /home). My system is HiDPI.

Perhaps I should file a bug report [here](https://bugs.launchpad.net/ubuntu/+source/gdebi) (where I have not managed to locate anything similar in the existing reports), or hope that Mint 19.1 fixes the problem.

**Comment by clefebvre** [comment]
No, that's on us alright... but it's not gdebi, it's aptdaemon..

**Comment by kolayne** [comment]
That's annoying a lot. Is there any news on this?

**Comment by clefebvre** [comment]
Can you still reproduce this with these: 

[Sandbox.zip](https://github.com/linuxmint/gdebi/files/4532723/Sandbox.zip)

Looking at the code, this looks like it shouldn't happen anymore. The scrolledview has a minimum height of 300px defined.

**Comment by LinuxOnTheDesktop** [comment]
I have just encountered the same problem on Mint 20. I have HiDPI scaling set to 2, which makes my screen height less than Mint recommends, but: (1) still!; (2) I had hoped to use fractional scaling on Mint 20, but it is unworkable on the computer concerned.

Screenshot:

![image](https://user-images.githubusercontent.com/47056543/88752334-945e8500-d151-11ea-9961-b4a919d15aab.png)
