### ISSUE TITLE
Add possibility to change keyserver

### ISSUE THREAD

**Issue by jm4R** [linuxmint/gdebi#15]
Keyserver is hardcoded to `keyserver.ubuntu.com`. It connects by default by TCP port `11371` which is often a problem when OS is behind a corporation environment. Please add at least a choice to change it to `hkp://keyserver.ubuntu.com:80` which could solve many troubles:

there are many problems like that on the internet like such:
https://stackoverflow.com/questions/51983144/error-installing-sbt-on-ubuntu-18-04-gpg-keyserver-receive-failed-invalid-ar

I don't know if it is the best issue to make such feature request, this probably should have been done in `Software Sources` GUI

**Comment by gm10** [comment]
This got nothing to do with gdebi and has already been address in mintsources.
