### ISSUE TITLE
Install .deb issues on linux mint alpha version

### ISSUE THREAD

**Issue by bomdia** [linuxmint/gdebi#16]
PROBLEM:
gdebi-gtk stop working without any alert to the user when pressing install
ACTION:
I'm trying to install last versione of google chrome and the latest version of atom  and i get the messagge that is visible in the screenshoot
SCREENSHOOT
![Schermata 2019-06-24 alle 15 42 16](https://user-images.githubusercontent.com/1759618/60032568-2373b080-96a7-11e9-9988-159469c34668.png)
WORKSPACE
Linux mint 19 last update for alpha channel
vmware fusion on mojave 
plain install without any other thing

**Comment by bomdia** [comment]
@clefebvre any thought on this?

**Comment by clefebvre** [comment]
Ah yes, that's just an issue with the ALPHA. It'll be ok going forward once we move to 19.2. It's to do with APT priorities. nothing to do with gdebi itself.
