### ISSUE TITLE
System hourglass does not show when pointer is over the gdebi window . .

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/gdebi#2]
. . rather, a small black one does. I thought that Mint 18.1 aimed to remove this sort of pointer inconsistency.

**Comment by xenopeek** [comment]
I can't reproduce this on Linux Mint 18.3 Cinnamon. When GDebi is installing a package, hovering the mouse over the GDebi windows shows the system hourglass pointer as expected. If the issue happens again, please go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) on the current version of Linux Mint.
