### ISSUE TITLE
Error message box not scaling

### ISSUE THREAD

**Issue by schorschii** [linuxmint/gdebi#22]
If the package installation fails, the error message text box does not scale with the window. It's very complicated to view the entire error message in this small text box:
![Bildschirmfoto vom 2022-04-02 17-51-06](https://user-images.githubusercontent.com/17480795/161390997-e0a1e794-9480-468c-8d3b-771d75b70b1c.png)

**Comment by clefebvre** [comment]
https://github.com/linuxmint/aptdaemon/commit/abbeedb39581adb994d12b023a6d194da6daf8e7
