### ISSUE TITLE
System too unresponsive when installing via gbedi

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/gdebi#3]
If, at least on my old core2Duo system - which does, though, have 8GB RAM and a SSD - one installs, say, KingSoft Office, or GoogleEarth, or, indeed, anything fairly large, the system becomes very unresponsive. Can this situation be improved? I wouldn't mind a slightly slower installation, in return for increased responsiveness.

**Comment by xenopeek** [comment]
Questions like these are better asked on the forums.
