### ISSUE TITLE
Suggestion: make colour of 'all dependencies satisfied' bar less alarming

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/gdebi#4]
At present the bar is orange, which seems a bit close to red to me. How about green, or blue, or yellow? Green might make the most sense (though perhaps not the same shade of green as is used for the - itself potentially confusing* - 'same version of package is already installed' message).

Thanks.

* In fact, I have actually encountered people who were confused by this.

**Comment by SketchNI** [comment]
I'd like to bump this and recommend changing the color to something like: #3498db
