### ISSUE TITLE
.flatpak support

### ISSUE THREAD

**Issue by orschiro** [linuxmint/gdebi#6]
Dear all,

Can we add support for `.flatpak` files? Not all Flatpaks are available from the software center and hence you need to download a flatpak file from the web, sometimes.

Having a GUI frontend to install those files would be nice, in my opinion.

Thank you!

**Comment by xenopeek** [comment]
This feature request can't go anywhere here. Gdebi is a simple front-end for dpkg and dpkg can't handle flatpak. It requires some other (new?) component to do `flatpak install --from yourfile.flatpakref`. I suggest you make the feature request here https://github.com/linuxmint/linuxmint/issues.

**Comment by xenopeek** [comment]
I think https://github.com/linuxmint/mintinstall/issues/178 is the same feature request, on mintinstall.
