### ISSUE TITLE
[Dependency Issue] GKSU is being removed in 18.04

### ISSUE THREAD

**Issue by feren** [linuxmint/gdebi#8]
So, I noticed that, in Linux Mint 18.3, your forked GDebi still uses what seems to be GKSU as a way to authenticate the installation or reinstallation of packages. However, if you don't know already, gksu as a package has been removed entirely from the Ubuntu 18.04 Repos, due to it being depreciated. So this is an issue to solely warn you guys at the Mint Team to get what's left of GKSU dialogs changed over to PKEXEC or similar...

**Comment by feren** [comment]
Fixed in the latest GDEBI on Mint 19 Tara Repos, it seems.

**Comment by feren** [comment]
Actually, I'll keep it open for now, seems to only work when ran from Terminal right now...

**Comment by xenopeek** [comment]
We're aware of gksu removal. For those tools that weren't moved to polkit before, work is ongoing as part of Linux Mint 19 development cycle.
