### ISSUE TITLE
Gdebi on Debian Password Error

### ISSUE THREAD

**Issue by ghost** [linuxmint/gdebi#9]
I have GDebi on my Debian 9.4 and it is causing a problem when it asks for a password to run it as a root, even if I put a correct password it again asks me for a password. So i have to use terminal. This bug is also reported on Debian Bug Reporter. Im not sure its an dependency issue or gdebi issue please fix thanks :)

**Comment by jatin-cbs** [comment]
After trying on different distros this problem is on most of the distributions.

**Comment by clefebvre** [comment]
hi @jatin-cbs, this is a patched version of gdebi for Linux Mint. Are you sure you're running this one?
